//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapi_test.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int IdBook { get; set; }
        public string Title { get; set; }
        public string Sinopsis { get; set; }
        public string Author { get; set; }
        public string Editorial { get; set; }
        public string Lenguage { get; set; }
        public string Formatt { get; set; }
        public string Genre { get; set; }
        public int Available { get; set; }
    }
}
